#!/bin/bash
if [ ! -d nng ]; then
  rm -rf deps nng build && mkdir deps
  git clone --depth 1 https://github.com/nanomsg/nng && cd nng
else
  cd nng
  git pull
  git submodule update --init --recursive
fi

mkdir -p build && cd build
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_MESSAGE=NEVER -DCMAKE_INSTALL_PREFIX=$(pwd)/../../deps .. -DNNG_TESTS=OFF -DNNG_TOOLS=OFF -DNNG_ENABLE_NNGCAT=OFF -DNNG_ENABLE_COVERAGE=OFF
make MACOSX_DEPLOYMENT_TARGET=10.15 all install
